baseURL = 'https://alcops.dev/'
languageCode = 'en-us'
title = 'ALCops'

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"

[params]
description = "A community driven collection of code analyzers for the AL programming language of Microsoft Dynamics 365 Business Central."
github_repo = "https://github.com/ALCops/alcops.dev"
github_project_repo = "https://github.com/ALCops/Analyzers"
offlineSearch = true
[params.ui]
showLightDarkModeMenu = true
sidebar_menu_compact = true
sidebar_menu_foldable = true
ul_show = 1

[markup]
[markup.goldmark]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true

[[menus.main]]
name = "Docs"
weight = 96
url = "docs/"
pre = "<i class='fa-solid fa-book'></i>"
post = ""

[[menus.main]]
name = "Rules"
weight = 97
url = "docs/analyzers/"
pre = "<i class='fa-solid fa-list-check'></i>"
post = ""

[[menus.main]]
name = "Get help"
weight = 98
url = "docs/get-help/"
pre = "<i class='fa-solid fa-life-ring'></i>"
post = ""

[[menus.main]]
name = "GitHub"
weight = 99
url = "https://github.com/ALCops"
pre = "<i class='fab fa-github'></i>"
post = ""

[caches]
  [caches.images]
    dir = ':cacheDir/images'
